name: Append article to reading list

on:
  repository_dispatch:
    types: ["rl-append"]

concurrency:
  group: append-to-reading-list

jobs:
  append-to-reading-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1

      - name: Append to reading list
        env:
          RL_INPUT_JSON: ${{ toJSON(github.event.client_payload) }}
        run: go run github.com/pythoncrazy/listofreading add

      - name: Commit changes
        run: |
          git config user.email "readinglistauto@supersketchy.me"
          git config user.name "Automatic update"
          git add readingList.csv
          git commit -m "Automated reading list update on $(date)"
          git push -u origin main

  build-deploy:
    needs: append-to-reading-list
    uses: ./.github/workflows/build.yml
    secrets: inherit
